- README.md
- index.html
- package.json
> #1 RENAME to parvenu

- .travis.yml
- package.json
> #4 ADD build on ci

- .vscode/launch.json
- src/scenes/Ware.test.ts
- src/scenes/i-inventory.ts
- src/scenes/i-logic.ts
- src/scenes/i-ware.ts
- src/scenes/inventory.test.ts
- src/scenes/inventory.ts
- src/scenes/logic.integration.test.ts
- src/scenes/logic.test.ts
- src/scenes/logic.ts
- src/scenes/logicBuilder.ts
- src/scenes/mainScene.ts
- src/scenes/ware.ts
- src/scenes/wareType.ts
- test/mocha.opts
- tsconfig.json
> ADD #10 As a player I want to trade 3 different wares

- .codecov.yml
- package.json
- src/scenes/i-inventory.ts
- src/scenes/i-logic.ts
- src/scenes/i-ware.ts
- src/scenes/inventory.test.ts
- src/scenes/inventory.ts
- src/scenes/logic.test.ts
- src/scenes/logic.ts
- src/scenes/mainScene.ts
- src/scenes/ware.ts
> 22 as a player i want to see ware quantities

- .travis.yml
- README.md
- deployment/delete-build-dir-from-gitignore.sh
- package.json
> 27 as a user i want a deployed app

- src/scenes/City.config.ts
- src/scenes/City.test.ts
- src/scenes/City.ts
- src/scenes/IWareForCity.ts
- src/scenes/Ware.config.test.ts
- src/scenes/Ware.config.ts
- src/scenes/mainScene.ts
- src/scenes/ware.ts
- tslint.json
> 40 as a player i want dynamic pricing of wares

- package.json
- src/logic.config.ts
- src/scenes/City.test.ts
- src/scenes/City.ts
- src/scenes/ICity.ts
- src/scenes/Ware.test.ts
- src/scenes/inventory.test.ts
- src/scenes/inventory.ts
- src/scenes/logic.test.ts
- src/scenes/mainScene.ts
> 42 as a player i want consumption of resources for cities

- .prettierrc.json
> CONFIG #61 prettier for windows

- deployment/.automerge.yml
> CONFIG #68 add .automerge.yml

- src/logic/City.config.ts
- src/logic/City.test.ts
- src/logic/City.ts
- src/logic/ICity.ts
- src/logic/Logic.test.ts
- src/scenes/MainScene.ts
> 45 as a player i want cities to produce wares

- package.json
- tslint.json
> CONFIG #76 no focused tests (disallow it.only)

- index.html
> ADD #88 sentry to base html

- .travis.yml
- Dockerfile
- README.md
- deployment/server/index.js
- heroku.yml
> 93 as a developer i want deployed dev branches

- src/Color.ts
- src/Game.config.ts
- src/scenes/GameOverScene.ts
- src/scenes/LoadingScene.ts
- src/scenes/MainScene.ts
- src/scenes/TextBuyPrice.ts
- src/scenes/TextSellPrice.ts
- src/scenes/keys.ts
> 97 as a player i want a fast starting game

- src/Color.ts
- src/logic/Logic.ts
- src/logic/Ware.ts
- src/scenes/CitySelectionScene.ts
- src/scenes/LoadingScene.ts
- src/scenes/MainScene.ts
- src/scenes/TableScene.ts
- src/scenes/TextBuyPrice.ts
- src/scenes/TextSellPrice.ts
> 101 as a player i want a more streamlined table layout

- README.md
> ADD #110 badges UPDATE README.md

- index.html
> ADD #122 google analytics

- .travis.yml
> CONFIG #158 remove node 8 launch in Travis CI

- src/scenes/FactoryScene.ts
- src/scenes/MainScene.ts
- src/scenes/TextFactoryCount.ts
- src/scenes/WareButton.ts
- src/utils/ObjectKeys.ts
> 157 as a player i can only produce wares in city that can produce the ware type

- src/logic/City.test.ts
- src/logic/City.ts
- src/logic/ICity.ts
- src/logic/Logic.test.ts
- src/logic/Logic.ts
- src/logic/Player.test.ts
- src/logic/Player.ts
- src/scenes/BuildFactoryButton.ts
- src/scenes/FactoryScene.ts
- src/scenes/TextCityWareQuantity.ts
- src/scenes/TextFactoryCount.ts
- src/scenes/TextWarehouseWareQuantity.ts
> 105 as a player i want building factories to cost money
